spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.zkqdwzqjlhylxicmixel
    password: YOUR_SUPABASE_DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

supabase:
  url: YOUR_SUPABASE_PROJECT_URL
  anon-key: YOUR_SUPABASE_ANON_KEY
