import type { Category, PaymentMethod, RepeatRule, Transaction } from './types';

export const INITIAL_ASSET = 2750000;

export const accountBookCategories: Category[] = [
  { id: 1, name: '식비', color: '#F97316', isDefault: true },
  { id: 2, name: '교통', color: '#2563EB', isDefault: true },
  { id: 3, name: '쇼핑', color: '#DB2777', isDefault: true },
  { id: 4, name: '카페', color: '#8B5A2B', isDefault: true },
  { id: 5, name: '기타', color: '#64748B', isDefault: true },
  { id: 6, name: '월급', color: '#16A34A', isDefault: true },
  { id: 7, name: '용돈', color: '#7C3AED', isDefault: true },
];

export const accountBookPaymentMethods: PaymentMethod[] = [
  { id: 1, name: '카드' },
  { id: 2, name: '현금' },
  { id: 3, name: '계좌이체' },
];

export const accountBookRepeatRules: RepeatRule[] = [
  { id: 1, frequency: 'monthly', interval: 1, startDate: '2026-04-05', endDate: null },
  { id: 2, frequency: 'weekly', interval: 1, startDate: '2026-04-07', endDate: null },
];

export const accountBookTransactions: Transaction[] = [
  {
    id: 1,
    type: 'income',
    amount: 3200000,
    title: '4월 월급',
    memo: '정기 급여',
    date: '2026-04-01',
    categoryId: 6,
    paymentMethodId: 3,
    repeatRuleId: null,
  },
  {
    id: 2,
    type: 'expense',
    amount: 12800,
    title: '출근 지하철',
    date: '2026-04-02',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 3,
    type: 'expense',
    amount: 48500,
    title: '대박삼겹살',
    memo: '친구랑 저녁',
    date: '2026-04-02',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 4,
    type: 'income',
    amount: 50000,
    title: '이모가 용돈 줌',
    date: '2026-04-02',
    categoryId: 7,
    paymentMethodId: 2,
    repeatRuleId: null,
  },
  {
    id: 5,
    type: 'expense',
    amount: 5400,
    title: '지브라운 라떼',
    memo: '오전 회의 전',
    date: '2026-04-03',
    categoryId: 4,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 6,
    type: 'expense',
    amount: 14900,
    title: '음악 스트리밍',
    memo: '월 구독',
    date: '2026-04-05',
    categoryId: 5,
    paymentMethodId: 1,
    repeatRuleId: 1,
  },
  {
    id: 7,
    type: 'expense',
    amount: 32000,
    title: '장보기',
    date: '2026-04-06',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 8,
    type: 'expense',
    amount: 12800,
    title: '정기 교통비',
    date: '2026-04-07',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: 2,
  },
  {
    id: 9,
    type: 'expense',
    amount: 89000,
    title: '봄 셔츠',
    memo: '세일 구매',
    date: '2026-04-12',
    categoryId: 3,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 10,
    type: 'expense',
    amount: 7800,
    title: '카페 모카',
    date: '2026-04-18',
    categoryId: 4,
    paymentMethodId: 2,
    repeatRuleId: null,
  },
  {
    id: 11,
    type: 'income',
    amount: 180000,
    title: '중고거래 입금',
    memo: '책상 판매',
    date: '2026-04-20',
    categoryId: 5,
    paymentMethodId: 3,
    repeatRuleId: null,
  },
  {
    id: 12,
    type: 'expense',
    amount: 42000,
    title: '주말 브런치',
    date: '2026-04-25',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 13,
    type: 'income',
    amount: 3200000,
    title: '5월 월급',
    memo: '정기 급여',
    date: '2026-05-01',
    categoryId: 6,
    paymentMethodId: 3,
    repeatRuleId: null,
  },
  {
    id: 14,
    type: 'expense',
    amount: 16700,
    title: '출근 교통비',
    date: '2026-05-01',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 15,
    type: 'expense',
    amount: 52000,
    title: '마라탕 저녁',
    memo: '친구 모임',
    date: '2026-05-02',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 16,
    type: 'expense',
    amount: 6100,
    title: '아이스 라떼',
    date: '2026-05-03',
    categoryId: 4,
    paymentMethodId: 2,
    repeatRuleId: null,
  },
  {
    id: 17,
    type: 'expense',
    amount: 14900,
    title: '음악 스트리밍',
    memo: '월 구독',
    date: '2026-05-05',
    categoryId: 5,
    paymentMethodId: 1,
    repeatRuleId: 1,
  },
  {
    id: 18,
    type: 'expense',
    amount: 74200,
    title: '장보기',
    memo: '일주일 식재료',
    date: '2026-05-06',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 19,
    type: 'expense',
    amount: 12800,
    title: '정기 교통비',
    date: '2026-05-07',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: 2,
  },
  {
    id: 20,
    type: 'income',
    amount: 80000,
    title: '용돈',
    date: '2026-05-08',
    categoryId: 7,
    paymentMethodId: 2,
    repeatRuleId: null,
  },
  {
    id: 21,
    type: 'expense',
    amount: 132000,
    title: '운동화',
    memo: '봄맞이 교체',
    date: '2026-05-10',
    categoryId: 3,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 22,
    type: 'expense',
    amount: 9800,
    title: '카페 작업',
    date: '2026-05-11',
    categoryId: 4,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 23,
    type: 'expense',
    amount: 38500,
    title: '초밥 점심',
    date: '2026-05-12',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 24,
    type: 'expense',
    amount: 25000,
    title: '택시',
    memo: '비 오는 날',
    date: '2026-05-13',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 25,
    type: 'income',
    amount: 120000,
    title: '중고거래 입금',
    memo: '의자 판매',
    date: '2026-05-14',
    categoryId: 5,
    paymentMethodId: 3,
    repeatRuleId: null,
  },
  {
    id: 26,
    type: 'expense',
    amount: 67800,
    title: '가족 외식',
    date: '2026-05-15',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 27,
    type: 'expense',
    amount: 45600,
    title: '생활용품',
    date: '2026-05-16',
    categoryId: 3,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 28,
    type: 'expense',
    amount: 5400,
    title: '아메리카노',
    date: '2026-05-17',
    categoryId: 4,
    paymentMethodId: 2,
    repeatRuleId: null,
  },
  {
    id: 29,
    type: 'expense',
    amount: 31800,
    title: '회사 근처 점심',
    memo: '5월 18일 점심',
    date: '2026-05-18',
    categoryId: 1,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
  {
    id: 30,
    type: 'expense',
    amount: 3900,
    title: '버스',
    date: '2026-05-18',
    categoryId: 2,
    paymentMethodId: 1,
    repeatRuleId: null,
  },
];
